"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class CreateEmvDataDukptDecryptRequest(object):
    """Implementation of the 'CreateEmvDataDukptDecryptRequest' model.

    Attributes:
        ksn (str): Key serial number

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ksn": "ksn",
    }

    def __init__(
        self,
        ksn=None):
        """Initialize a CreateEmvDataDukptDecryptRequest instance."""
        # Initialize members of the class
        self.ksn = ksn

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ksn =\
            dictionary.get("ksn")\
            if dictionary.get("ksn")\
                else None

        # Return an object of this model
        return cls(ksn)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ksn=self.ksn
        return (
            f"{self.__class__.__name__}("
            f"ksn={_ksn!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ksn=self.ksn
        return (
            f"{self.__class__.__name__}("
            f"ksn={_ksn!s}, "
            f")"
        )
