"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from pagarmeapisdk.api_helper import APIHelper
from pagarmeapisdk.models.create_checkout_card_installment_option_request import (
    CreateCheckoutCardInstallmentOptionRequest,
)
from pagarmeapisdk.models.create_payment_authentication_request import (
    CreatePaymentAuthenticationRequest,
)


class CreateCheckoutCreditCardPaymentRequest(object):
    """Implementation of the 'CreateCheckoutCreditCardPaymentRequest' model.

    Checkout card payment request

    Attributes:
        statement_descriptor (str): Card invoice text descriptor
        installments (List[CreateCheckoutCardInstallmentOptionRequest]): Payment
            installment options
        authentication (CreatePaymentAuthenticationRequest): Creates payment
            authentication
        capture (bool): Authorize and capture?

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "statement_descriptor": "statement_descriptor",
        "installments": "installments",
        "authentication": "authentication",
        "capture": "capture",
    }

    _optionals = [
        "statement_descriptor",
        "installments",
        "authentication",
        "capture",
    ]

    def __init__(
        self,
        statement_descriptor=APIHelper.SKIP,
        installments=APIHelper.SKIP,
        authentication=APIHelper.SKIP,
        capture=APIHelper.SKIP):
        """Initialize a CreateCheckoutCreditCardPaymentRequest instance."""
        # Initialize members of the class
        if statement_descriptor is not APIHelper.SKIP:
            self.statement_descriptor = statement_descriptor
        if installments is not APIHelper.SKIP:
            self.installments = installments
        if authentication is not APIHelper.SKIP:
            self.authentication = authentication
        if capture is not APIHelper.SKIP:
            self.capture = capture

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        statement_descriptor =\
            dictionary.get("statement_descriptor")\
            if dictionary.get("statement_descriptor")\
                else APIHelper.SKIP
        installments = None
        if dictionary.get("installments") is not None:
            installments = [
                CreateCheckoutCardInstallmentOptionRequest.from_dictionary(x)
                    for x in dictionary.get("installments")
            ]
        else:
            installments = APIHelper.SKIP
        authentication =\
            CreatePaymentAuthenticationRequest.from_dictionary(
                dictionary.get("authentication"))\
                if "authentication" in dictionary.keys()\
                else APIHelper.SKIP
        capture =\
            dictionary.get("capture")\
            if "capture" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(statement_descriptor,
                   installments,
                   authentication,
                   capture)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _statement_descriptor=(
            self.statement_descriptor
            if hasattr(self, "statement_descriptor")
            else None
        )
        _installments=(
            self.installments
            if hasattr(self, "installments")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _capture=(
            self.capture
            if hasattr(self, "capture")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"statement_descriptor={_statement_descriptor!r}, "
            f"installments={_installments!r}, "
            f"authentication={_authentication!r}, "
            f"capture={_capture!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _statement_descriptor=(
            self.statement_descriptor
            if hasattr(self, "statement_descriptor")
            else None
        )
        _installments=(
            self.installments
            if hasattr(self, "installments")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _capture=(
            self.capture
            if hasattr(self, "capture")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"statement_descriptor={_statement_descriptor!s}, "
            f"installments={_installments!s}, "
            f"authentication={_authentication!s}, "
            f"capture={_capture!s}, "
            f")"
        )
