# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.models.create_cancel_charge_split_rules_request import CreateCancelChargeSplitRulesRequest
from pagarmeapisdk.models.create_split_request import CreateSplitRequest


class CreateCancelChargeRequest(object):

    """Implementation of the 'CreateCancelChargeRequest' model.

    Request for canceling a charge.

    Attributes:
        amount (int): The amount that will be canceled.
        split_rules (list of CreateCancelChargeSplitRulesRequest): The split
            rules request
        split (list of CreateSplitRequest): Splits
        operation_reference (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operation_reference": 'operation_reference',
        "amount": 'amount',
        "split_rules": 'split_rules',
        "split": 'split'
    }

    def __init__(self,
                 operation_reference=None,
                 amount=None,
                 split_rules=None,
                 split=None):
        """Constructor for the CreateCancelChargeRequest class"""

        # Initialize members of the class
        self.amount = amount
        self.split_rules = split_rules
        self.split = split
        self.operation_reference = operation_reference

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        operation_reference = dictionary.get('operation_reference')
        amount = dictionary.get('amount')
        split_rules = None
        if dictionary.get('split_rules') is not None:
            split_rules = [CreateCancelChargeSplitRulesRequest.from_dictionary(x) for x in dictionary.get('split_rules')]
        split = None
        if dictionary.get('split') is not None:
            split = [CreateSplitRequest.from_dictionary(x) for x in dictionary.get('split')]

        # Return an object of this model
        return cls(operation_reference,
                   amount,
                   split_rules,
                   split)
