"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from pagarmeapisdk.api_helper import APIHelper


class CreateGooglePayIntermediateSigningKeyRequest(object):
    """Implementation of the 'CreateGooglePayIntermediateSigningKeyRequest' model.

    The GooglePay Intermediate Signing Key Request

    Attributes:
        signed_key (str): Uma mensagem codificada em Base64 com a descrição de
            pagamento da chave.
        signatures (List[str]): Verifica se a origem da chave de assinatura
            intermediária é o Google. É codificada em Base64 e criada usando o ECDSA.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "signed_key": "signed_key",
        "signatures": "signatures",
    }

    _optionals = [
        "signed_key",
        "signatures",
    ]

    _nullables = [
        "signed_key",
        "signatures",
    ]

    def __init__(
        self,
        signed_key=APIHelper.SKIP,
        signatures=APIHelper.SKIP):
        """Initialize a CreateGooglePayIntermediateSigningKeyRequest instance."""
        # Initialize members of the class
        if signed_key is not APIHelper.SKIP:
            self.signed_key = signed_key
        if signatures is not APIHelper.SKIP:
            self.signatures = signatures

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        signed_key =\
            dictionary.get("signed_key")\
            if "signed_key" in dictionary.keys()\
                else APIHelper.SKIP
        signatures =\
            dictionary.get("signatures")\
            if "signatures" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(signed_key,
                   signatures)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _signed_key=(
            self.signed_key
            if hasattr(self, "signed_key")
            else None
        )
        _signatures=(
            self.signatures
            if hasattr(self, "signatures")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"signed_key={_signed_key!r}, "
            f"signatures={_signatures!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _signed_key=(
            self.signed_key
            if hasattr(self, "signed_key")
            else None
        )
        _signatures=(
            self.signatures
            if hasattr(self, "signatures")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"signed_key={_signed_key!s}, "
            f"signatures={_signatures!s}, "
            f")"
        )
