# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.api_helper import APIHelper
from pagarmeapisdk.models.create_split_options_request import CreateSplitOptionsRequest


class CreateSplitRequest(object):

    """Implementation of the 'CreateSplitRequest' model.

    Split

    Attributes:
        mtype (str): Split type
        amount (int): Amount
        recipient_id (str): Recipient id
        options (CreateSplitOptionsRequest): The split options request
        split_rule_id (str): Rule code used in cancellation.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "amount": 'amount',
        "recipient_id": 'recipient_id',
        "options": 'options',
        "split_rule_id": 'split_rule_id'
    }

    _optionals = [
        'options',
        'split_rule_id',
    ]

    def __init__(self,
                 mtype=None,
                 amount=None,
                 recipient_id=None,
                 options=APIHelper.SKIP,
                 split_rule_id=APIHelper.SKIP):
        """Constructor for the CreateSplitRequest class"""

        # Initialize members of the class
        self.mtype = mtype 
        self.amount = amount 
        self.recipient_id = recipient_id 
        if options is not APIHelper.SKIP:
            self.options = options 
        if split_rule_id is not APIHelper.SKIP:
            self.split_rule_id = split_rule_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get("type") if dictionary.get("type") else None
        amount = dictionary.get("amount") if dictionary.get("amount") else None
        recipient_id = dictionary.get("recipient_id") if dictionary.get("recipient_id") else None
        options = CreateSplitOptionsRequest.from_dictionary(dictionary.get('options')) if 'options' in dictionary.keys() else APIHelper.SKIP
        split_rule_id = dictionary.get("split_rule_id") if dictionary.get("split_rule_id") else APIHelper.SKIP
        # Return an object of this model
        return cls(mtype,
                   amount,
                   recipient_id,
                   options,
                   split_rule_id)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'mtype={self.mtype!r}, '
                f'amount={self.amount!r}, '
                f'recipient_id={self.recipient_id!r}, '
                f'options={(self.options if hasattr(self, "options") else None)!r}, '
                f'split_rule_id={(self.split_rule_id if hasattr(self, "split_rule_id") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'mtype={self.mtype!s}, '
                f'amount={self.amount!s}, '
                f'recipient_id={self.recipient_id!s}, '
                f'options={(self.options if hasattr(self, "options") else None)!s}, '
                f'split_rule_id={(self.split_rule_id if hasattr(self, "split_rule_id") else None)!s})')
