# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.models.create_address_request import CreateAddressRequest


class CreateSellerRequest(object):

    """Implementation of the 'CreateSellerRequest' model.

    TODO: type model description here.

    Attributes:
        name (string): Name
        code (string): Seller's code identification
        description (string): Description
        document (string): Document number (individual / company)
        address (CreateAddressRequest): Address
        mtype (string): Person type (individual / company)
        metadata (dict): Metadata

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "metadata": 'metadata',
        "code": 'code',
        "description": 'description',
        "document": 'document',
        "address": 'address',
        "mtype": 'type'
    }

    def __init__(self,
                 name=None,
                 metadata=None,
                 code=None,
                 description=None,
                 document=None,
                 address=None,
                 mtype=None):
        """Constructor for the CreateSellerRequest class"""

        # Initialize members of the class
        self.name = name
        self.code = code
        self.description = description
        self.document = document
        self.address = address
        self.mtype = mtype
        self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('name')
        metadata = dictionary.get('metadata')
        code = dictionary.get('code')
        description = dictionary.get('description')
        document = dictionary.get('document')
        address = CreateAddressRequest.from_dictionary(dictionary.get('address')) if dictionary.get('address') else None
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(name,
                   metadata,
                   code,
                   description,
                   document,
                   address,
                   mtype)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
