"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from pagarmeapisdk.api_helper import APIHelper


class GetSetupResponse(object):
    """Implementation of the 'GetSetupResponse' model.

    Response object for getting the setup from a subscription

    Attributes:
        id (str): The model property of type str.
        description (str): The model property of type str.
        amount (int): The model property of type int.
        status (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "description": "description",
        "amount": "amount",
        "status": "status",
    }

    _optionals = [
        "id",
        "description",
        "amount",
        "status",
    ]

    _nullables = [
        "id",
        "description",
        "amount",
        "status",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        description=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        status=APIHelper.SKIP):
        """Initialize a GetSetupResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if description is not APIHelper.SKIP:
            self.description = description
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if status is not APIHelper.SKIP:
            self.status = status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if "id" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if "status" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   description,
                   amount,
                   status)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"description={_description!r}, "
            f"amount={_amount!r}, "
            f"status={_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"description={_description!s}, "
            f"amount={_amount!s}, "
            f"status={_status!s}, "
            f")"
        )
