# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.api_helper import APIHelper


class GetBillingAddressResponse(object):

    """Implementation of the 'GetBillingAddressResponse' model.

    Response object for getting a billing address

    Attributes:
        street (str): The model property of type str.
        number (str): The model property of type str.
        zip_code (str): The model property of type str.
        neighborhood (str): The model property of type str.
        city (str): The model property of type str.
        state (str): The model property of type str.
        country (str): The model property of type str.
        complement (str): The model property of type str.
        line_1 (str): Line 1 for address
        line_2 (str): Line 2 for address

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "street": 'street',
        "number": 'number',
        "zip_code": 'zip_code',
        "neighborhood": 'neighborhood',
        "city": 'city',
        "state": 'state',
        "country": 'country',
        "complement": 'complement',
        "line_1": 'line_1',
        "line_2": 'line_2'
    }

    _optionals = [
        'street',
        'number',
        'zip_code',
        'neighborhood',
        'city',
        'state',
        'country',
        'complement',
        'line_1',
        'line_2',
    ]

    _nullables = [
        'street',
        'number',
        'zip_code',
        'neighborhood',
        'city',
        'state',
        'country',
        'complement',
        'line_1',
        'line_2',
    ]

    def __init__(self,
                 street=APIHelper.SKIP,
                 number=APIHelper.SKIP,
                 zip_code=APIHelper.SKIP,
                 neighborhood=APIHelper.SKIP,
                 city=APIHelper.SKIP,
                 state=APIHelper.SKIP,
                 country=APIHelper.SKIP,
                 complement=APIHelper.SKIP,
                 line_1=APIHelper.SKIP,
                 line_2=APIHelper.SKIP):
        """Constructor for the GetBillingAddressResponse class"""

        # Initialize members of the class
        if street is not APIHelper.SKIP:
            self.street = street 
        if number is not APIHelper.SKIP:
            self.number = number 
        if zip_code is not APIHelper.SKIP:
            self.zip_code = zip_code 
        if neighborhood is not APIHelper.SKIP:
            self.neighborhood = neighborhood 
        if city is not APIHelper.SKIP:
            self.city = city 
        if state is not APIHelper.SKIP:
            self.state = state 
        if country is not APIHelper.SKIP:
            self.country = country 
        if complement is not APIHelper.SKIP:
            self.complement = complement 
        if line_1 is not APIHelper.SKIP:
            self.line_1 = line_1 
        if line_2 is not APIHelper.SKIP:
            self.line_2 = line_2 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        street = dictionary.get("street") if "street" in dictionary.keys() else APIHelper.SKIP
        number = dictionary.get("number") if "number" in dictionary.keys() else APIHelper.SKIP
        zip_code = dictionary.get("zip_code") if "zip_code" in dictionary.keys() else APIHelper.SKIP
        neighborhood = dictionary.get("neighborhood") if "neighborhood" in dictionary.keys() else APIHelper.SKIP
        city = dictionary.get("city") if "city" in dictionary.keys() else APIHelper.SKIP
        state = dictionary.get("state") if "state" in dictionary.keys() else APIHelper.SKIP
        country = dictionary.get("country") if "country" in dictionary.keys() else APIHelper.SKIP
        complement = dictionary.get("complement") if "complement" in dictionary.keys() else APIHelper.SKIP
        line_1 = dictionary.get("line_1") if "line_1" in dictionary.keys() else APIHelper.SKIP
        line_2 = dictionary.get("line_2") if "line_2" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(street,
                   number,
                   zip_code,
                   neighborhood,
                   city,
                   state,
                   country,
                   complement,
                   line_1,
                   line_2)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'street={(self.street if hasattr(self, "street") else None)!r}, '
                f'number={(self.number if hasattr(self, "number") else None)!r}, '
                f'zip_code={(self.zip_code if hasattr(self, "zip_code") else None)!r}, '
                f'neighborhood={(self.neighborhood if hasattr(self, "neighborhood") else None)!r}, '
                f'city={(self.city if hasattr(self, "city") else None)!r}, '
                f'state={(self.state if hasattr(self, "state") else None)!r}, '
                f'country={(self.country if hasattr(self, "country") else None)!r}, '
                f'complement={(self.complement if hasattr(self, "complement") else None)!r}, '
                f'line_1={(self.line_1 if hasattr(self, "line_1") else None)!r}, '
                f'line_2={(self.line_2 if hasattr(self, "line_2") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'street={(self.street if hasattr(self, "street") else None)!s}, '
                f'number={(self.number if hasattr(self, "number") else None)!s}, '
                f'zip_code={(self.zip_code if hasattr(self, "zip_code") else None)!s}, '
                f'neighborhood={(self.neighborhood if hasattr(self, "neighborhood") else None)!s}, '
                f'city={(self.city if hasattr(self, "city") else None)!s}, '
                f'state={(self.state if hasattr(self, "state") else None)!s}, '
                f'country={(self.country if hasattr(self, "country") else None)!s}, '
                f'complement={(self.complement if hasattr(self, "complement") else None)!s}, '
                f'line_1={(self.line_1 if hasattr(self, "line_1") else None)!s}, '
                f'line_2={(self.line_2 if hasattr(self, "line_2") else None)!s})')
