"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from pagarmeapisdk.api_helper import APIHelper


class GetIntegrationResponse(object):
    """Implementation of the 'GetIntegrationResponse' model.

    Attributes:
        code (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": "code",
    }

    _optionals = [
        "code",
    ]

    def __init__(
        self,
        code=APIHelper.SKIP):
        """Initialize a GetIntegrationResponse instance."""
        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(code)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"code={_code!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"code={_code!s}, "
            f")"
        )
