# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.api_helper import APIHelper


class GetPriceBracketResponse(object):

    """Implementation of the 'GetPriceBracketResponse' model.

    Response object for getting a price bracket

    Attributes:
        start_quantity (int): The model property of type int.
        price (int): The model property of type int.
        end_quantity (int): The model property of type int.
        overage_price (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start_quantity": 'start_quantity',
        "price": 'price',
        "end_quantity": 'end_quantity',
        "overage_price": 'overage_price'
    }

    _optionals = [
        'start_quantity',
        'price',
        'end_quantity',
        'overage_price',
    ]

    _nullables = [
        'start_quantity',
        'price',
        'end_quantity',
        'overage_price',
    ]

    def __init__(self,
                 start_quantity=APIHelper.SKIP,
                 price=APIHelper.SKIP,
                 end_quantity=APIHelper.SKIP,
                 overage_price=APIHelper.SKIP):
        """Constructor for the GetPriceBracketResponse class"""

        # Initialize members of the class
        if start_quantity is not APIHelper.SKIP:
            self.start_quantity = start_quantity 
        if price is not APIHelper.SKIP:
            self.price = price 
        if end_quantity is not APIHelper.SKIP:
            self.end_quantity = end_quantity 
        if overage_price is not APIHelper.SKIP:
            self.overage_price = overage_price 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start_quantity = dictionary.get("start_quantity") if "start_quantity" in dictionary.keys() else APIHelper.SKIP
        price = dictionary.get("price") if "price" in dictionary.keys() else APIHelper.SKIP
        end_quantity = dictionary.get("end_quantity") if "end_quantity" in dictionary.keys() else APIHelper.SKIP
        overage_price = dictionary.get("overage_price") if "overage_price" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(start_quantity,
                   price,
                   end_quantity,
                   overage_price)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'start_quantity={(self.start_quantity if hasattr(self, "start_quantity") else None)!r}, '
                f'price={(self.price if hasattr(self, "price") else None)!r}, '
                f'end_quantity={(self.end_quantity if hasattr(self, "end_quantity") else None)!r}, '
                f'overage_price={(self.overage_price if hasattr(self, "overage_price") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'start_quantity={(self.start_quantity if hasattr(self, "start_quantity") else None)!s}, '
                f'price={(self.price if hasattr(self, "price") else None)!s}, '
                f'end_quantity={(self.end_quantity if hasattr(self, "end_quantity") else None)!s}, '
                f'overage_price={(self.overage_price if hasattr(self, "overage_price") else None)!s})')
