# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.api_helper import APIHelper
from pagarmeapisdk.models.get_customer_response import GetCustomerResponse


class GetCheckoutPaymentSettingsResponse(object):

    """Implementation of the 'GetCheckoutPaymentSettingsResponse' model.

    Checkout Payment Settings Response

    Attributes:
        success_url (string): Success Url
        payment_url (string): Payment Url
        accepted_payment_methods (list of string): Accepted Payment Methods
        status (string): Status
        customer (GetCustomerResponse): Customer
        amount (int): Payment amount
        default_payment_method (string): Default Payment Method
        gateway_affiliation_id (string): Gateway Affiliation Id

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success_url": 'success_url',
        "payment_url": 'payment_url',
        "accepted_payment_methods": 'accepted_payment_methods',
        "status": 'status',
        "customer": 'customer',
        "amount": 'amount',
        "default_payment_method": 'default_payment_method',
        "gateway_affiliation_id": 'gateway_affiliation_id'
    }

    _optionals = [
        'customer',
        'amount',
        'default_payment_method',
        'gateway_affiliation_id',
    ]

    def __init__(self,
                 success_url=None,
                 payment_url=None,
                 accepted_payment_methods=None,
                 status=None,
                 customer=APIHelper.SKIP,
                 amount=APIHelper.SKIP,
                 default_payment_method=APIHelper.SKIP,
                 gateway_affiliation_id=APIHelper.SKIP):
        """Constructor for the GetCheckoutPaymentSettingsResponse class"""

        # Initialize members of the class
        self.success_url = success_url 
        self.payment_url = payment_url 
        self.accepted_payment_methods = accepted_payment_methods 
        self.status = status 
        if customer is not APIHelper.SKIP:
            self.customer = customer 
        if amount is not APIHelper.SKIP:
            self.amount = amount 
        if default_payment_method is not APIHelper.SKIP:
            self.default_payment_method = default_payment_method 
        if gateway_affiliation_id is not APIHelper.SKIP:
            self.gateway_affiliation_id = gateway_affiliation_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        success_url = dictionary.get("success_url") if dictionary.get("success_url") else None
        payment_url = dictionary.get("payment_url") if dictionary.get("payment_url") else None
        accepted_payment_methods = dictionary.get("accepted_payment_methods") if dictionary.get("accepted_payment_methods") else None
        status = dictionary.get("status") if dictionary.get("status") else None
        customer = GetCustomerResponse.from_dictionary(dictionary.get('customer')) if 'customer' in dictionary.keys() else APIHelper.SKIP 
        amount = dictionary.get("amount") if dictionary.get("amount") else APIHelper.SKIP
        default_payment_method = dictionary.get("default_payment_method") if dictionary.get("default_payment_method") else APIHelper.SKIP
        gateway_affiliation_id = dictionary.get("gateway_affiliation_id") if dictionary.get("gateway_affiliation_id") else APIHelper.SKIP
        # Return an object of this model
        return cls(success_url,
                   payment_url,
                   accepted_payment_methods,
                   status,
                   customer,
                   amount,
                   default_payment_method,
                   gateway_affiliation_id)
