"""pagarmeapisdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from pagarmeapisdk.api_helper import APIHelper
from pagarmeapisdk.models.create_address_request import (
    CreateAddressRequest,
)
from pagarmeapisdk.models.create_phones_request import (
    CreatePhonesRequest,
)


class UpdateCustomerRequest(object):
    """Implementation of the 'UpdateCustomerRequest' model.

    Request for updating a customer

    Attributes:
        name (str): Name
        email (str): Email
        document (str): Document number
        mtype (str): Person type
        address (CreateAddressRequest): Address
        metadata (Dict[str, str]): Metadata
        phones (CreatePhonesRequest): The model property of type CreatePhonesRequest.
        code (str): Código de referência do cliente no sistema da loja. Max: 52
            caracteres
        gender (str): Gênero do cliente
        document_type (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "email": "email",
        "document": "document",
        "mtype": "type",
        "address": "address",
        "metadata": "metadata",
        "phones": "phones",
        "code": "code",
        "gender": "gender",
        "document_type": "document_type",
    }

    _optionals = [
        "name",
        "email",
        "document",
        "mtype",
        "address",
        "metadata",
        "phones",
        "code",
        "gender",
        "document_type",
    ]

    def __init__(
        self,
        name=APIHelper.SKIP,
        email=APIHelper.SKIP,
        document=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        address=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        phones=APIHelper.SKIP,
        code=APIHelper.SKIP,
        gender=APIHelper.SKIP,
        document_type=APIHelper.SKIP):
        """Initialize a UpdateCustomerRequest instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        if email is not APIHelper.SKIP:
            self.email = email
        if document is not APIHelper.SKIP:
            self.document = document
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if address is not APIHelper.SKIP:
            self.address = address
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if phones is not APIHelper.SKIP:
            self.phones = phones
        if code is not APIHelper.SKIP:
            self.code = code
        if gender is not APIHelper.SKIP:
            self.gender = gender
        if document_type is not APIHelper.SKIP:
            self.document_type = document_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        document =\
            dictionary.get("document")\
            if dictionary.get("document")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        address =\
            CreateAddressRequest.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        phones =\
            CreatePhonesRequest.from_dictionary(
                dictionary.get("phones"))\
                if "phones" in dictionary.keys()\
                else APIHelper.SKIP
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        gender =\
            dictionary.get("gender")\
            if dictionary.get("gender")\
                else APIHelper.SKIP
        document_type =\
            dictionary.get("document_type")\
            if dictionary.get("document_type")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(name,
                   email,
                   document,
                   mtype,
                   address,
                   metadata,
                   phones,
                   code,
                   gender,
                   document_type)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _phones=(
            self.phones
            if hasattr(self, "phones")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _gender=(
            self.gender
            if hasattr(self, "gender")
            else None
        )
        _document_type=(
            self.document_type
            if hasattr(self, "document_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"email={_email!r}, "
            f"document={_document!r}, "
            f"mtype={_mtype!r}, "
            f"address={_address!r}, "
            f"metadata={_metadata!r}, "
            f"phones={_phones!r}, "
            f"code={_code!r}, "
            f"gender={_gender!r}, "
            f"document_type={_document_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _phones=(
            self.phones
            if hasattr(self, "phones")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _gender=(
            self.gender
            if hasattr(self, "gender")
            else None
        )
        _document_type=(
            self.document_type
            if hasattr(self, "document_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"email={_email!s}, "
            f"document={_document!s}, "
            f"mtype={_mtype!s}, "
            f"address={_address!s}, "
            f"metadata={_metadata!s}, "
            f"phones={_phones!s}, "
            f"code={_code!s}, "
            f"gender={_gender!s}, "
            f"document_type={_document_type!s}, "
            f")"
        )
