# -*- coding: utf-8 -*-

"""
pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pagarmeapisdk.api_helper import APIHelper
from pagarmeapisdk.models.create_card_request import CreateCardRequest
from pagarmeapisdk.models.create_payment_origin_request import CreatePaymentOriginRequest


class UpdateChargeCardRequest(object):

    """Implementation of the 'UpdateChargeCardRequest' model.

    Request for updating card data

    Attributes:
        update_subscription (bool): Indicates if the subscriptions using this
            card must also be updated
        card_id (str): Card id
        card (CreateCardRequest): Card data
        recurrence (bool): Indicates a recurrence
        initiated_type (str): TODO: type description here.
        recurrence_model (str): TODO: type description here.
        payment_origin (CreatePaymentOriginRequest): TODO: type description
            here.
        indirect_acceptor (str): Business model identifier

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "update_subscription": 'update_subscription',
        "card_id": 'card_id',
        "card": 'card',
        "recurrence": 'recurrence',
        "initiated_type": 'initiated_type',
        "recurrence_model": 'recurrence_model',
        "payment_origin": 'payment_origin',
        "indirect_acceptor": 'indirect_acceptor'
    }

    _optionals = [
        'initiated_type',
        'recurrence_model',
        'payment_origin',
        'indirect_acceptor',
    ]

    def __init__(self,
                 update_subscription=None,
                 card_id=None,
                 card=None,
                 recurrence=None,
                 initiated_type=APIHelper.SKIP,
                 recurrence_model=APIHelper.SKIP,
                 payment_origin=APIHelper.SKIP,
                 indirect_acceptor=APIHelper.SKIP):
        """Constructor for the UpdateChargeCardRequest class"""

        # Initialize members of the class
        self.update_subscription = update_subscription 
        self.card_id = card_id 
        self.card = card 
        self.recurrence = recurrence 
        if initiated_type is not APIHelper.SKIP:
            self.initiated_type = initiated_type 
        if recurrence_model is not APIHelper.SKIP:
            self.recurrence_model = recurrence_model 
        if payment_origin is not APIHelper.SKIP:
            self.payment_origin = payment_origin 
        if indirect_acceptor is not APIHelper.SKIP:
            self.indirect_acceptor = indirect_acceptor 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        update_subscription = dictionary.get("update_subscription") if "update_subscription" in dictionary.keys() else None
        card_id = dictionary.get("card_id") if dictionary.get("card_id") else None
        card = CreateCardRequest.from_dictionary(dictionary.get('card')) if dictionary.get('card') else None
        recurrence = dictionary.get("recurrence") if "recurrence" in dictionary.keys() else None
        initiated_type = dictionary.get("initiated_type") if dictionary.get("initiated_type") else APIHelper.SKIP
        recurrence_model = dictionary.get("recurrence_model") if dictionary.get("recurrence_model") else APIHelper.SKIP
        payment_origin = CreatePaymentOriginRequest.from_dictionary(dictionary.get('payment_origin')) if 'payment_origin' in dictionary.keys() else APIHelper.SKIP
        indirect_acceptor = dictionary.get("indirect_acceptor") if dictionary.get("indirect_acceptor") else APIHelper.SKIP
        # Return an object of this model
        return cls(update_subscription,
                   card_id,
                   card,
                   recurrence,
                   initiated_type,
                   recurrence_model,
                   payment_origin,
                   indirect_acceptor)
